tap 'homebrew/dupes'
tap 'homebrew/versions'

brew 'coreutils'
brew 'go'
brew 'ghq'
brew 'hg'
brew 'git'
brew 'openssl'
brew 'peco'
brew 'slackcat'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'imagemagick'
brew 'wget'
brew 'z'
brew 'zsh'
brew 'gnu-tar'
brew 'gnu-sed'
brew 'hugo'
brew 'highlight'
brew 'kubernetes-cli'
brew 'jq'
brew 'zsh-syntax-highlighting'
brew 'zsh-completions'
brew 'homebrew/dupes/screen'
brew 'homebrew/versions/node4-lts'
brew 'ruby-build'
brew 'rbenv'
brew 'jsonnet'
brew 'gotags'
brew 'ctags'

tap 'caskroom/cask'
cask 'atom'
cask 'dockertoolbox'
cask 'dropbox'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'karabiner'
cask 'slack'
cask 'vagrant'
cask 'virtualbox'
cask 'spectacle'

tap 'caskroom/fonts'
cask 'font-devicons'
cask 'font-fontawesome'
cask 'font-noto-sans'
cask 'font-noto-sans-japanese'
cask 'font-noto-serif'
# vim: set ft=ruby :
